[project]
name = "qwen3-30b-a3b-full-parameter-post-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
download-formate = [
    "datasets>=4.0.0",
    "huggingface-hub>=0.36.2",
]
preprocess-mix = [
    "py-data-juicer[generic]>=1.5.1",
]
